//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordeev_41.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good_Table
    {
        public int GoodId { get; set; }
        public string GoodName { get; set; }
        public decimal GoodPrice { get; set; }
        public string GoodWeight { get; set; }
        public string GoodIngridients { get; set; }
        public string GoodCategory { get; set; }
        public string GoodCalorific { get; set; }
        public byte[] GoodPhoto { get; set; }
    }
}
