//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordeev_41.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsItem
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string Text { get; set; }
        public System.DateTime CreationDate { get; set; }
        public byte[] Photo { get; set; }
        public string Author { get; set; }
    }
}
